#!/bin/sh

curl -X POST -d @./TestPatients/Cesection/Patient_Cesection.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cesection/RelatedPerson_Cesection.json http://127.0.0.1:8080/baseDstu3/RelatedPerson -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cesection/Patient_BabyCesection.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cesection/Observation_Weight_BabyCesection.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cesection/Observation_BMI_Cesection.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cesection/Claim_Birth_Cesection.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cesection/Claim_Delivery_Cesection.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"

curl -X POST -d @./TestPatients/Cistica/Patient_Cistica.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cistica/RelatedPerson_Cistica.json http://127.0.0.1:8080/baseDstu3/RelatedPerson -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cistica/Patient_BabyCistica.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cistica/Observation_Weight_BabyCistica.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cistica/Observation_BMI_Cistica.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cistica/Claim_Birth_Cistica.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cistica/Claim_Delivery_Cistica.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Cistica/Claim_Risk_Cistica.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"

curl -X POST -d @./TestPatients/Dixon/Patient_Dixon.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Dixon/RelatedPerson_Dixon.json http://127.0.0.1:8080/baseDstu3/RelatedPerson -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Dixon/Patient_BabyDixon.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Dixon/Observation_Weight_BabyDixon.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Dixon/Observation_Weight_BabyDixon_Day3.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Dixon/Observation_Weight_BabyDixon_Day5.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Dixon/QuestionnaireResponse_BF_Dixon_Day4.json http://127.0.0.1:8080/baseDstu3/QuestionnaireResponse -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Dixon/QuestionnaireResponse_BF_Dixon_Day5.json http://127.0.0.1:8080/baseDstu3/QuestionnaireResponse -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Dixon/QuestionnaireResponse_Dixon_Day4.json http://127.0.0.1:8080/baseDstu3/QuestionnaireResponse -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Dixon/QuestionnaireResponse_Dixon_Day5.json http://127.0.0.1:8080/baseDstu3/QuestionnaireResponse -H "Content-Type: application/json"

curl -X POST -d @./TestPatients/Glands/Patient_Glands.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Glands/RelatedPerson_Glands.json http://127.0.0.1:8080/baseDstu3/RelatedPerson -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Glands/Patient_BabyGlands.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Glands/Observation_Weight_BabyGlands.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Glands/Observation_BMI_Glands.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Glands/Claim_Birth_Glands.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Glands/Claim_Delivery_Glands.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Glands/Claim_Risk_Glands.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"

curl -X POST -d @./TestPatients/Sweets/Patient_Sweets.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Sweets/RelatedPerson_Sweets.json http://127.0.0.1:8080/baseDstu3/RelatedPerson -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Sweets/Patient_BabySweets.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Sweets/Observation_Weight_BabySweets.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Sweets/Observation_BMI_Sweets.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Sweets/Claim_Birth_Sweets.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Sweets/Claim_Delivery_Sweets.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Sweets/Claim_Risk_Sweets.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"

curl -X POST -d @./TestPatients/Wellgood/Patient_Wellgood.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Wellgood/RelatedPerson_Wellgood.json http://127.0.0.1:8080/baseDstu3/RelatedPerson -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Wellgood/Patient_BabyWellgood.json http://127.0.0.1:8080/baseDstu3/Patient -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Wellgood/Observation_Weight_BabyWellgood.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Wellgood/Observation_BMI_Wellgood.json http://127.0.0.1:8080/baseDstu3/Observation -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Wellgood/Claim_Birth_Wellgood.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"
curl -X POST -d @./TestPatients/Wellgood/Claim_Delivery_Wellgood.json http://127.0.0.1:8080/baseDstu3/Claim -H "Content-Type: application/json"
